config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'stored_content/create'
  get 'stored_content' => 'stored_content#list'

end

app/models/stored_content.rb
require 'open-uri'

class StoredContent
  include Mongoid::Document

  field :url
  field :content, default: []

  def process_and_save
    process
    save
  end

  def process
    content_from_url = []

    page = Nokogiri::HTML(open(url))
    elements = page.css('h1, h2, h3, a')

    elements.each do |element|
      if element.name == 'a'
        content_from_url.push({ 
          :element => element.name, 
          :value => { :href => element['href'], :text => element.text } 
        })
      else
        content_from_url.push({
          :element => element.name,
          :value => element.text
        })
      end
    end

    self.content = content_from_url
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/stored_content_controller.rb
class StoredContentController < ApplicationController
  def create
    @stored_content = StoredContent.new(url: params[:url])
    @stored_content.process_and_save
    render json: @stored_content
  end

  def list
    @stored_content = StoredContent.all
    render json: @stored_content
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @stored_content = StoredContent.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stored_content_helper.rb
module StoredContentHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ContentIndexing</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome to Content Indexing API</h1>

<p>The API provides ways to store and retrieve specific content from publicly available pages in the internet. Content in tags H1, H2, H3 and A (links) will be stored.</p>
<p>See documentation at <a href="http://github.com/diegoversiani/content-indexing">http://github.com/diegoversiani/content-indexing</a></p>

<p>If you want to see the API in action, call the actions bellow:</p>

<h3>Actions:</h3>

<p>
  <code>Retrieve</code> stored content: <%= button_to 'Call retrieve', stored_content_path, method: :get %>
</p>

<p>
  <code>Store</code> content from url:<br>

  <%= form_tag(stored_content_create_path, method: :get) do |f| %>
    <%= label_tag :url %>
    <%= text_field_tag :url, nil, placeholder: 'http://google.com', required: true %>
    <%= submit_tag 'Store content' %>
  <% end %>
</p>